version: "3"
services:
  db:
      image: mariadb
      container_name: "${DB_SERVICE_NAME:-mariadb}"
      environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-test}
          - MYSQL_DATABASE=${MYSQL_DATABASE:-radio}
      volumes:
          - ./database:/var/lib/mysql
      ports:
          - "${DB_PORT:-3306}:3306"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: "${PMA_SERVICE_NAME:-phpmyadmin}"
      environment:
          - PMA_HOST=db
          - PMA_PORT= 3306
  #    restart: always
      ports:
          - "${PMA_PORT:-8080}:80"
      volumes:
          - /sessions
      links:
          - db